formatter: markdown table

header-from: header.md

settings:
  anchor: false

output:
  file: "README.md"
  mode: replace
  template: |-
    {{ .Content }}

content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}



